//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Nutresa.Imagix.DataAccess.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbBigNutresaImagixEntities : DbContext
    {
        public dbBigNutresaImagixEntities()
            : base("name=dbBigNutresaImagixEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NI_ConfigurationGroup> NI_ConfigurationGroup { get; set; }
        public virtual DbSet<NI_Program> NI_Program { get; set; }
    
        public virtual ObjectResult<NI_GET_CONTENT_CONFIGURATION_PROVIDERS_SETTINGS_Result> NI_GET_CONTENT_CONFIGURATION_PROVIDERS_SETTINGS(Nullable<int> programId, string node)
        {
            var programIdParameter = programId.HasValue ?
                new ObjectParameter("programId", programId) :
                new ObjectParameter("programId", typeof(int));
    
            var nodeParameter = node != null ?
                new ObjectParameter("node", node) :
                new ObjectParameter("node", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NI_GET_CONTENT_CONFIGURATION_PROVIDERS_SETTINGS_Result>("NI_GET_CONTENT_CONFIGURATION_PROVIDERS_SETTINGS", programIdParameter, nodeParameter);
        }
    }
}
