//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Big.Nutresa.Imagix.DataAccess.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NI_ConfigurationGroup
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public int Active { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ContentProviderClass { get; set; }
        public string ContentProviderSettings { get; set; }
        public int ProgramId { get; set; }
    
        public virtual NI_Program NI_Program { get; set; }
    }
}
